name: Deploy static site to EC2

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy files to EC2 (rsync)
        run: |
          rsync -az --delete \
            --exclude ".git*" \
            --exclude ".github" \
            --exclude "README.md" \
            -e "ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=yes" \
            ./ "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.DEPLOY_PATH }}"

      - name: Reload Nginx (optional)
        run: |
          ssh -i ~/.ssh/ec2_key -o StrictHostKeyChecking=yes \
            "${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}" \
            "sudo systemctl reload nginx || true"

